apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: info-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: info
  rules:
  - http:
      paths:
      - path: /info(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: info-svc
            port:
              number: 80

