apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx-svc
spec:
  selector:
    app: nginx-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443

