apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/mynginx:local
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: my-webserver-pv
      volumes:
      - name: my-webserver-pv
        persistentVolumeClaim:
          claimName: webserver-pvc

