apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - infinitytek.xyz
    secretName: tls-secret
  rules:
  - host: infinitytek.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-svc
            port:
              number: 80
      - path: /fincalc
        pathType: Prefix
        backend:
          service:
            name: fincalc-ui-svc
            port:
              number: 80
